#$ -S /bin/bash
#$ -N FUSION
#$ -cwd
#$ -o weight.o
#$ -e weight.e
#$ -V
#$ -q all.q
#$ -sync y
#$ -t 1-60

export b=/genetics/bin
export f=/genetics/bin/FUSION.compute_weights.R
export d=/scratch/tempjhz22/FUSION/data/FUSION
export o=/scratch/tempjhz22/FUSION

function get_weight_in_parallel ()
{
   parallel --dry-run -j1 --env b --env o --env d --env f --env p -C' ' '
   echo {1} {2} {3}; \
   cd $o/1KG/{1}; \
   $p --make-bed --missing-phenotype -999 --pheno $d.pheno --covar $d.covar --bfile {1} --maf 0.01 --pheno-name {1} --out {1}; \
   $f --bfile={1} --tmp={1}_t --covar={1}.cov --PATH_gcta=$b/gcta_nr_robust --PATH_plink=$b/plink-1.9 --PATH_gemma=$b/gemma_1_thread \
      --crossval=5 --models=top1,lasso,enet --save_hsq --out={1}'
}

export chr=$1

if [ ! -z "$chr" ]
then
   export sl=$(($(awk '$2==chr' chr=$chr $d/CpG.txt | wc -l)/60+1))
   awk '$2==chr' chr=$chr $d/CpG.txt | awk 'NR==(v-1)*sl+1, NR==v*sl' v=$SGE_TASK_ID sl=$sl | get_weight_in_parallel
else
   export sl=$(($(wc -l $d/CpG.txt | cut -d' ' -f1)/60+1))
   awk 'NR==(v-1)*sl+1, NR==v*sl' v=$SGE_TASK_ID sl=$sl $d/CpG.txt | get_weight_in_parallel
fi
